### ISSUE TITLE
Missing Value?

### ISSUE THREAD

**Issue by evokercodex** [phantomfirefox/MissingNo#4]
https://github.com/phantomfirefox/MissingNo/blob/de5ba12f17a9f32e195789a9467bd1c4e44c2212/Pokemon%20Natures.csv#L4

and several lines below? Should you store NULL or 0?

**Comment by phantomfirefox** [comment]
No you are right. The file is incomplete in that there should be 25 natures with each sub column complete. I just stopped halfway. The natures and buffs/debuffs are found here for reference: https://bulbapedia.bulbagarden.net/wiki/Nature

**Comment by phantomfirefox** [comment]
I updated the example :)
